language: python
sudo: false
python: 3.5
addons:
  postgresql: "9.4"
install:
  - pip install -U pip wheel
  - pip install -r requirements.txt
script:
  - flake8 decisions paatos
  - pytest -vvv --cov decisions
after_success: coveralls
